USE Ecommerce

CREATE TABLE tbProduto(
	PRO_CODIGO INT NOT NULL PRIMARY KEY IDENTITY,
	PRO_NOME VARCHAR(30) NOT NULL,
	PRO_DESCRICAO VARCHAR(50) NULL,
	PRO_PRECO INT NOT NULL,
	PRO_ESTOQUE INT NOT NULL
)

CREATE TABLE tbCliente(
	CLI_CODIGO INT PRIMARY KEY NOT NULL IDENTITY,
	CLI_NOME VARCHAR(30) NOT NULL,
	CLI_EMAIL VARCHAR(50) NULL,
	CLI_CIDADE VARCHAR(30) NOT NULL,
	CLI_RUA VARCHAR(30) NOT NULL,
	CLI_NUMERO INT NOT NULL
)

CREATE TABLE tbClieteTelefone(
	CLT_CODIGO INT PRIMARY KEY NOT NULL IDENTITY,
	CLT_TELEFONE CHAR(11) NOT NULL,
	CLI_CODIGO INT NOT NULL FOREIGN KEY REFERENCES 
	tbCliente(CLI_CODIGO) ON DELETE CASCADE
)

CREATE TABLE tbPedido(
	PED_CODIGO INT PRIMARY KEY NOT NULL IDENTITY,
	CLI_CODIGO INT NOT NULL FOREIGN KEY REFERENCES
	tbCliente(CLI_CODIGO) ON DELETE NO ACTION,
	PED_HORA_DATA DATETIME NOT NULL DEFAULT GETDATE(),
	PED_VALOR_TOTAL INT NOT NULL
)

CREATE TABLE tbPedidoProduto(
	PEP_CODIGO INT NOT NULL PRIMARY KEY IDENTITY,
	CLI_CODIGO INT NOT NULL FOREIGN KEY REFERENCES 
	tbCliente(CLI_CODIGO) ON DELETE NO ACTION,
	PED_CODIGO INT NOT NULL FOREIGN KEY REFERENCES 
	tbPedido(PED_CODIGO) ON DELETE NO ACTION,
	PEP_QTD INT NOT NULL
)